[package]
name = "minswp"
version = "0.1.0"
authors = ["Walker Crouse <Walker.Crouse@bjss.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "^0.33.0"
bitflags = "^1.2.1"
rand = "^0.7.3"
