[window]
title = "minswpr"
width = 800
height = 600
bg_color = "#ffffff"

[fonts]
"board.cell" = { path = "/usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf", pt = 12 }

[board]
width = 9
height = 9
mine_frequency = 0.123

[board.cells]
width = 15
height = 15
color = "#c0c0c0"
border_width = 1
border_color = "#000000"
revealed_color = "#4269f5"
mines = { color = "#000000", width = 5, height = 5 }
flags = { color = "#ff0000", width = 5, height = 5 }
