[window]
title = "minswpr"
width = 800
height = 600
bg_color = "#ffffff"

[fonts]
"board.cell" = { path = "/usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf", pt = 24 }

[board]
width = 8
height = 8
# mine_frequency = 0.078
mine_frequency = 0.1

[board.cells]
width = 50
height = 50
color = "#f57842"
border_width = 1
border_color = "#000000"
revealed_color = "#4269f5"
mines = { color = "#000000", width = 20, height = 20 }
