[window]
title = "minswpr"
dimen = { x = 800, y = 600 }
bg_color = "#ffffff"

[fonts]
"board.cell" = { path = "/usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf", pt = 12 }
"control.flag_counter" = { path = "/usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf", pt = 22 }
"control.stopwatch" = { path = "/usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf", pt = 22 }

[layout]
padding = 5
color = "#000000"
guides = false

[control]
height = 35
spacer_height = 5
spacer_color = "#000000"
color = "#c0c0c0"
padding = 5
reset_button_dimen = { x = 25, y = 25 }
reset_button_color = "#ffff00"

[control.flag_counter]
dimen = {x = 40, y = 25 }
color = "#000000"
padding = 1

[control.stopwatch]
dimen = {x = 40, y = 25 }
color = "#000000"
padding = 1

[board]
dimen = { x = 9, y = 9 }
num_mines = 10

[board.cells]
dimen = { x = 15, y = 15 }
color = "#c0c0c0"
border_width = 1
border_color = "#000000"
revealed_color = "#4269f5"

[board.cells.mines]
color = "#000000"
dimen = { x = 5, y = 5 }
revealed_color = "#ff0000"

[board.cells.flags]
color = "#ff0000"
dimen = { x = 5, y = 5 }
