[window]
title = "minswpr"
dimen = { x = 800, y = 600 }
bg_color = "#ffffff"

[fonts]
# "board.cell" = { path = "/usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf", pt = 12 }
"board.cell" = { path = "/Library/Fonts/Arial.ttf", pt = 12 }

[control]
height = 50

[board]
dimen = { x = 9, y = 9 }
mine_frequency = 0.123

[board.cells]
dimen = { x = 15, y = 15 }
color = "#c0c0c0"
border_width = 1
border_color = "#000000"
revealed_color = "#4269f5"

[board.cells.mines]
color = "#000000"
dimen = { x = 5, y = 5 }
revealed_color = "#ff0000"

[board.cells.flags]
color = "#ff0000"
dimen = { x = 5, y = 5 }
